### ISSUE TITLE
Change master branch to main

### ISSUE THREAD

**Issue by oncleben31** [hacf-fr/awesome-francophone-home-assistant#10]
If we want to reference this list in [the awesome list of awesome list](https://github.com/sindresorhus/awesome), we need to move to `main` branch.

**Comment by Quentame** [comment]
Indeed, see [requirements to submit an Awesome list](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md)

**Comment by oncleben31** [comment]
Done.
