### ISSUE TITLE
Déplacer les liens de Paradis Artificiel dans la section archives

### ISSUE THREAD

**Issue by oncleben31** [hacf-fr/awesome-francophone-home-assistant#35]
D'après les bonnes pratique des awesome-list, nous devrions déplacer les liens périmés dans une section archives.

Je pense que nous devons déplacer le contenu de Paradis Artificiel dans cette section archive.

@hacf-fr/developers @hacf-fr/masters qu'en pensez vous ?

**Comment by McFlyPartages** [comment]
Ok pour moi

**Comment by Quentame** [comment]
OK pour moi

**Comment by oncleben31** [comment]
Allez GO. Je bosse sur la PR
