### ISSUE TITLE
Ajouter un dark theme

### ISSUE THREAD

**Issue by Quentame** [hacf-fr/awesome-francophone-home-assistant#58]
Y a-t-il vraiment besoin d'une description ?

Tout est dans le titre 😉

**Comment by oncleben31** [comment]
Il faudra attende que la fonctionnalité de swithc mode sombre mode standard soit déployée. Pour le moment réservées aux insiders (payant)

**Comment by Quentame** [comment]
C'est pas bien grave au pire

**Comment by oncleben31** [comment]
Il y a quand même un mode sombre qui s'affiche en fonction des préférences de l'OS de chaque utilisateur.
