### ISSUE TITLE
Ajouter le blog de faire ca soi même

### ISSUE THREAD

**Issue by oncleben31** [hacf-fr/awesome-francophone-home-assistant#63]

**Comment by Squale76** [comment]
@oncleben31, qu'est-ce que tu veux ajouter comme section `faire ça soi même` car il existe une section [Faites le vous même](https://github.com/hacf-fr/awesome-francophone-home-assistant#faites-le-vous-m%C3%AAme) ?

**Comment by oncleben31** [comment]
Je pensais à ce blog: https://faire-ca-soi-meme.fr/
Qui couvre parmis plein de sujet DIY la Zigate: passerelle universelle Zigbee made in France.

**Comment by Quentame** [comment]
Fermé par #69
